# 只允许手动和定时触发
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

stages:
  - prepare
  - sync_to_github
  - merge_github_pr
  - sync_from_github
  - finish

include:
  - local: '.gitlab/ci/sync_to_github.yml'
  - local: '.gitlab/ci/merge_github_pr.yml'
  - local: '.gitlab/ci/sync_from_github.yml'
  - local: '.gitlab/ci/finish.yml'