name: Batch Merge PRs from GitLab

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Merge PRs
        run: |
          cd tools/ci
          pip install -r requirements.txt
          python merge_github_prs.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITHUB_REPO: OpenSiFli/SiFli-SDK-ci